// Constant variables for action creator and Reducer's

//LOAN 
export const CREATE_LOAN = "CREATE_LOAN";
export const CREATE_LOAN_RED = "CREATE_LOAN_RED";
export const GET_LOAN = "GET_LOAN";
export const GET_LOAN_RED = "GET_LOAN_RED";
export const UPDATE_LOAN = "UPDATE_LOAN";
export const UPDATE_LOAN_RED = "UPDATE_LOAN_RED";
export const DELETE_LOAN = "DELETE_LOAN";
export const DELETE_LOAN_RED = "DELETE_LOAN_RED";

//SERVICES

export const CREATE_SERVICES = "CREATE_SERVICES";
export const CREATE_SERVICES_RED = "CREATE_SERVICES_RED";
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_RED = "GET_SERVICES_RED";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const UPDATE_SERVICES_RED = "UPDATE_SERVICES_RED";
export const DELETE_SERVICES = "DELETE_SERVICES";
export const DELETE_SERVICES_RED = "DELETE_SERVICES_RED";

//TESTIMONIAL

export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

//NEWSLATTER

export const CREATE_NEWSLATTER = "CREATE_NEWSLATTER";
export const CREATE_NEWSLATTER_RED = "CREATE_NEWSLATTER_RED";
export const GET_NEWSLATTER = "GET_NEWSLATTER";
export const GET_NEWSLATTER_RED = "GET_NEWSLATTER_RED";
export const UPDATE_NEWSLATTER = "UPDATE_NEWSLATTER";
export const UPDATE_NEWSLATTER_RED = "UPDATE_NEWSLATTER_RED";
export const DELETE_NEWSLATTER = "DELETE_NEWSLATTER";
export const DELETE_NEWSLATTER_RED = "DELETE_NEWSLATTER_RED";

//TEAM

export const CREATE_TEAM = "CREATE_TEAM";
export const CREATE_TEAM_RED = "CREATE_TEAM_RED";
export const GET_TEAM = "GET_TEAM";
export const GET_TEAM_RED = "GET_TEAM_RED";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const UPDATE_TEAM_RED = "UPDATE_TEAM_RED";
export const DELETE_TEAM = "DELETE_TEAM";
export const DELETE_TEAM_RED = "DELETE_TEAM_RED";

//CONTACT US
export const CREATE_CONTACT = "CREATE_CONTACT";
export const CREATE_CONTACT_RED = "CREATE_CONTACT_RED";
export const GET_CONTACT = "GET_CONTACT";
export const GET_CONTACT_RED = "GET_CONTACT_RED";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_RED = "UPDATE_CONTACT_RED";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_CONTACT_RED = "DELETE_CONTACT_RED";

//USERS
export const CREATE_USERS = "CREATE_USERS";
export const CREATE_USERS_RED = "CREATE_USERS_RED";
export const GET_USERS = "GET_USERS";
export const GET_USERS_RED = "GET_USERS_RED";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USERS_RED = "UPDATE_USERS_RED";
export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_RED = "DELETE_USERS_RED";

//PAYMENT

export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const CREATE_PAYMENT_RED = "CREATE_PAYMENT_RED";
export const GET_PAYMENT = "GET_PAYMENT";
export const GET_PAYMENT_RED = "GET_PAYMENT_RED";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const UPDATE_PAYMENT_RED = "UPDATE_PAYMENT_RED";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const DELETE_PAYMENT_RED = "DELETE_PAYMENT_RED";

// REPAYMENT

export const CREATE_REPAYMENT = "CREATE_REPAYMENT";
export const CREATE_REPAYMENT_RED = "CREATE_REPAYMENT_RED";
export const GET_REPAYMENT = "GET_REPAYMENT";
export const GET_REPAYMENT_RED = "GET_REPAYMENT_RED";
export const UPDATE_REPAYMENT = "UPDATE_REPAYMENT";
export const UPDATE_REPAYMENT_RED = "UPDATE_REPAYMENT_RED";
export const DELETE_REPAYMENT = "DELETE_REPAYMENT";
export const DELETE_REPAYMENT_RED = "DELETE_REPAYMENT_RED";